FROM node:4

ADD ./package.json /app/package.json
WORKDIR /app
RUN npm install
RUN npm install -g babel
VOLUME ["/data"]
ADD . /app
ENV NODE_ENV production
RUN npm run build
CMD NODE_PATH=. node index.js

EXPOSE 8080
