FROM node:4

ENV NODE_ENV production

ADD ./package.json /app/package.json
WORKDIR /app
RUN npm install
RUN npm install -g babel
VOLUME ["/data"]
ADD . /app
CMD NODE_PATH=. node index.js

EXPOSE 8080
